version: '3.7'
services:
  backend:
    build:
      context: ./backend
    image: nestjs-backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - "./backend/volume:/usr/src/app"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://dbuser:dbpassword@db:5432/dbname
  db:
    build:
      context: ./database
    image: postgres:12
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: dbname
  frontend:
    build:
      context: ./frontend
    image: reactjs-frontend
    container_name: frontend
    ports:
      - "4000:4000"
    volumes:
      - "./frontend/volume:/usr/src/app"
    depends_on:
      - backend

volumes:
  pgdata:
